### ISSUE TITLE
Line spacing too wide

### ISSUE THREAD

**Issue by aaronkollasch** [smittytone/PreviewText#1]
Thank you for sharing this app!

Using Menlo @ 12pt, Regular, Single spacing, the line spacing seems wider than I'd expect, almost like a 1.15 or 1.5 spacing. The same holds when I use SF Mono. I'd prefer to be able to reduce the line spacing beyond what is currently possible.

Compare PreviewText's preview with TextEdit on the same file:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/7785912/209986095-2873008f-c18b-4808-9c20-8643499eba89.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/7785912/209986825-a9f2ee82-e75b-4dbe-a470-ec9a01bcb56a.png">

**Comment by smittytone** [comment]
This is a bug, and it'll be fixed in the next release.

**Comment by aaronkollasch** [comment]
Works great, thanks!
