### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by ferben** [smittytone/PreviewText#4]
On my MAcBook Pro take whole memory:
<img width="644" alt="ScreenShot 2024-04-15 at 0 07 44" src="https://github.com/smittytone/PreviewText/assets/45659268/0ed78e08-3ca2-4db0-bcc2-cdec29ff8189">

**Comment by smittytone** [comment]
Thank you for mentioning this. I'm currently looking into it; other folks have seen this too. I cannot replicate it, but I'm continuing to explore.

**Comment by smittytone** [comment]
PS. @ferben, can you give me any idea about the circumstances when you encounter this? For example, are the thumbnailed files particularly large? Are there a great many files in the folder being thumbnailed?

**Comment by ferben** [comment]
I Think that caused some specific file (unexpected extension or somethink like that), but it must happen really fast: select file evoke QL shortcut and that's it -> no slow memory consumption raise while long computer run.

**Comment by smittytone** [comment]
I'm shortly going to release a new version which hopefully (🤞🏻) solves this issue.

**Comment by smittytone** [comment]
Version 1.0.5 released to the App Store. Marking this done pending results from users.
